// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivrhpkurnwlxadquzvox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cmhwa3VybndseGFkcXV6dm94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODE2ODIsImV4cCI6MjA3MzM1NzY4Mn0.-_cNCLE-SA2HqzWOIgJxKvmIbo_1BRGds8cV4Cjr-Cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});